# 00-Fundamentals
**Imports**

In [109]:
import torch
import numpy as np
# torch.__version__
# torch.cuda.is_available()

**Creating a scalar tensor**
- In tensor terms, a scalar is a zero-dimensional tensor

In [11]:
scalar = torch.tensor(7)
scalar.ndim

0

**Creating a vector tensor**

In [14]:
vector = torch.tensor([1,2])
vector.shape

torch.Size([2])

**Creating a matrix tensor**

In [24]:
MATRIX = torch.tensor([[1,2], [3,4]])
MATRIX.shape

torch.Size([2, 2])

**Creating a tensor**

In [25]:
TENSOR = torch.rand([3,3,3])
TENSOR.shape

torch.Size([3, 3, 3])

**Tensors containing only zeroes and ones**

In [28]:
zeros = torch.zeros(size=[2,4])
ones = torch.ones(size=[2,4])
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Creating a tensor with a range**

In [29]:
T_range = torch.arange(1,10,2)
T_range

tensor([1, 3, 5, 7, 9])

**Tensor with the shape of specific data**

In [32]:
T = torch.zeros_like(input=T_range)
T

tensor([0, 0, 0, 0, 0])

**Creating tensors with a specific data type**

In [37]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None,  # defaults to None, which uses the default tensor type
                               requires_grad=False)  # if True, operations perfromed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

**Get important information from tensor**
-  When you run into issues in PyTorch, it's very often one to do with one of the three attributes below.

In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")


Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Basic tensor operations**

In [43]:
T = torch.tensor([1, 2, 3])

# Addition
print(T + 10)

# Multiplication (element-wise)
print(T * 10)

tensor([11, 12, 13])
tensor([10, 20, 30])


**Matrix multiplication (dot products)**

Requires:
- That the inner dimensions of the matrices match
- That the resulting matrix has the shape of the outer dimensions

In [48]:
T = torch.tensor([1, 2, 3])
torch.matmul(T, T)

tensor(14)

**Shape mismatches**

In [57]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

tensor_C = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B)  # (this will error)
torch.matmul(tensor_A, tensor_C)  # (this won't)
torch.mm(tensor_A, tensor_B.T)  # (this neither)

# torch.mm is sort for torch.matmul

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

**Simple linear layer**

In [63]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix mutliplcation
linear = torch.nn.Linear(in_features=2,  # in_features = matches inner dimension of input
                         out_features=6)  # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


**Aggregation**

You may find some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.

In [69]:
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}")  # won't work without float datatype
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")


Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


**Positional min/max**

In [74]:
x = torch.arange(0, 100, 10)

# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")


Index where max value occurs: 9
Index where min value occurs: 0


**Changing data types**

In [77]:
tensor = torch.arange(10., 100., 10.)
print(f"Data type = {tensor.dtype}")
tensor_new = tensor.type(torch.int8) # Be aware that this is a copying procedure
print(f"Data type = {tensor_new.dtype}")


Data type = torch.float32
Data type = torch.int8


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

**Reshaping, stacking, squeezing and unsqueezing**

In [108]:
x = torch.arange(1.,8.)

# Reshaping
x_reshaped = x.reshape(1,7)
# x_reshaped

# Change view <- a view creates a new object THAT POINTS TO THE SAME TENSOR
z = x.view(1,7)
# z, z.shape

# Stacking
x_stacked = torch.stack([x]*5, dim=1)
# x_stacked

# Squeezing
x_squeezed = x_reshaped.squeeze()
# print(f"Previous tensor: {x_reshaped}")
# print(f"Previous shape: {x_reshaped.shape}")
# print(f"\nNew tensor: {x_squeezed}")
# print(f"New shape: {x_squeezed.shape}")

# Unsqueezing
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
# print(f"Previous tensor: {x_squeezed}")
# print(f"Previous shape: {x_squeezed.shape}")
# print(f"\nNew tensor: {x_unsqueezed}")
# print(f"New shape: {x_unsqueezed.shape}")

# Permuting
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**Combining with numpy**

In [111]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# array, tensor

# Tensor to NumPy array
tensor = torch.ones(7)  # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy()  # will be dtype=float32 unless changed
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Use GPU if available, else CPU**

In [113]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

1

## Exercises

In [115]:
# 2 - Create a random tensor with shape (7, 7).
t = torch.rand(7,7)
t

tensor([[0.3629, 0.1748, 0.2401, 0.5457, 0.7303, 0.5268, 0.6694],
        [0.3213, 0.4008, 0.2892, 0.9977, 0.6649, 0.5646, 0.9323],
        [0.4621, 0.4027, 0.1680, 0.1170, 0.5063, 0.6061, 0.5141],
        [0.1907, 0.0445, 0.5425, 0.9580, 0.9967, 0.6417, 0.0839],
        [0.0765, 0.5912, 0.8892, 0.4251, 0.8701, 0.1472, 0.6981],
        [0.4965, 0.0381, 0.8473, 0.4449, 0.0770, 0.4626, 0.7900],
        [0.2483, 0.8160, 0.1168, 0.9158, 0.9107, 0.8897, 0.5155]])

In [119]:
# 3 - Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
# (hint: you may have to transpose the second tensor).
t2 = torch.rand(1,7)
res = torch.mm(t,t2.T)
res

tensor([[1.0024],
        [1.2816],
        [1.0389],
        [0.9206],
        [1.1004],
        [1.0199],
        [1.5067]])

In [123]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
t = torch.rand(7,7)
t2 = torch.rand(1, 7)
res = torch.mm(t, t2.T)
res


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [124]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 
# (hint: you'll need to look into the documentation for torch.cuda for this one). 
# If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [133]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
torch.manual_seed(1234)
t1 = torch.rand(2,3).to("cuda")
t2 = torch.rand(2,3).to("cuda")
t1

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [137]:
# Perform a matrix multiplication on the tensors you created in 6 
# (again, you may have to adjust the shapes of one of the tensors).
res = torch.mm(t1,t2.T)
res

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [148]:
# Find the maximum and minimum values of the output of 7.
res.min(), res.max()

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

In [147]:
# Find the maximum and minimum index values of the output of 7.
res.argmin(), res.argmax()

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))

In [145]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions 
# removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the 
# first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
t = torch.rand((1, 1, 1, 10))
print(t, t.shape)
t_squeezed = t.squeeze()
print(t_squeezed, t_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
